// src/app/layout.tsx
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { cn } from '@/lib/utils' // shadcn
import { AuthProvider } from '@/context/AuthContext' // <-- Import
import Script from 'next/script'

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          'min-h-screen bg-background font-sans antialiased',
          inter.variable
        )}
      >
        <Script
          src="https://cdnjs.cloudflare.com/ajax/libs/lamejs/1.2.1/lame.min.js"
          strategy="afterInteractive"
        />
        {/* Wrap everything in the AuthProvider */}
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  )
}
